### ISSUE TITLE
can't run gui-subtrans.exe

### ISSUE THREAD

**Issue by eleven-monkey** [machinewrapped/gpt-subtrans#174]
I run gui-subtrans.exe from command line,but the gui did't show up and throw a error like this:

INFO: Initialising log
INFO: Loading stylesheet from C:\gui-subtrans\_internal\theme\subtrans.qss
Traceback (most recent call last):
  File "scripts\gui-subtrans.py", line 98, in <module>
  File "GUI\MainWindow.py", line 66, in __init__
  File "GUI\GuiInterface.py", line 201, in Startup
  File "GUI\GuiInterface.py", line 319, in _first_run
  File "GUI\FirstRunOptions.py", line 21, in __init__
TypeError: 'PySide6.QtWidgets.QDialog.__init__' called with wrong argument types:
  PySide6.QtWidgets.QDialog.__init__(GuiInterface)
Supported signatures:
  PySide6.QtWidgets.QDialog.__init__(Optional[PySide6.QtWidgets.QWidget] = None, PySide6.QtCore.Qt.WindowType = Default(Qt.WindowFlags))
[30036] Failed to execute script 'gui-subtrans' due to unhandled exception!

I tried latest 0.7.3 and 0.7.2,both throw the same error.

I tried on Windows 10 IoT 企业版

**Comment by machinewrapped** [comment]
Thanks for the report, should be fixed in 0.7.4:
https://github.com/machinewrapped/gpt-subtrans/releases/tag/v0.7.4
