### ISSUE TITLE
Issue with manually specifying Gemini models, always model not found

### ISSUE THREAD

**Issue by PeterDaveHello** [machinewrapped/gpt-subtrans#191]
When trying to use Gemini models, I'm unable to manually specify the model. I've tried `gemini-1.5-pro`, `gemini-1.5-flash`, and `gemini-1.5-flash-latest`, but all result in errors like:

```
Error: Unable to create provider client: Model gemini-1.5-flash not found
```

The default model works fine:

```
INFO: Translating with Gemini models/gemini-1.0-pro model
```

However, manually specifying `gemini-1.0-pro` or `models/gemini-1.0-pro` still fails.

OpenAI models work without issues, looks like the problem is specific to Gemini.

Environment:
- Linux Mint 21.3
- Python 3.10.12
- Latest master branch

Full error log:
```
(envsubtrans) peter ~/repos/subtitles/gpt-subtrans-gemini $ ./gemini-subtrans.sh -m gemini-1.0-pro -l "Traditional Chinese(zh_TW/cht)"test.srt
Activating virtual environment...
INFO: Initialising log
INFO: OpenAI SDK not installed. Azure provider will not be available
INFO: Anthropic SDK not installed. Claude provider will not be available
INFO: OpenAI SDK not installed. OpenAI provider will not be available
WARNING: All log messages before absl::InitializeLog() is called are written to STDERR
I0000 00:00:1722267191.490593 2274798 config.cc:230] gRPC experiments enabled: call_status_override_on_cancellation, event_engine_dns, event_engine_listener, http2_stats_fix, monitoring_experiment, pick_first_new, trace_record_callops, work_serializer_clears_time_cache
INFO: Using translation provider Gemini
Error: Unable to create provider client: Model gemini-1.0-pro not found
Traceback (most recent call last):
File "/home/peter/repos/subtitles/gpt-subtrans-gemini/PySubtitle/SubtitleTranslator.py", line 65, in init
self.client : TranslationClient = self.translation_provider.GetTranslationClient(self.settings)
File "/home/peter/repos/subtitles/gpt-subtrans-gemini/PySubtitle/Providers/Provider_Gemini.py", line 49, in GetTranslationClient
'model': self._get_true_name(self.selected_model),
File "/home/peter/repos/subtitles/gpt-subtrans-gemini/PySubtitle/Providers/Provider_Gemini.py", line 124, in _get_true_name
raise ValueError(f"Model {display_name} not found")
ValueError: Model gemini-1.0-pro not found

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
File "/home/peter/repos/subtitles/gpt-subtrans-gemini/scripts/gemini-subtrans.py", line 29, in <module>
translator : SubtitleTranslator = CreateTranslator(options)
File "/home/peter/repos/subtitles/gpt-subtrans-gemini/scripts/subtrans_common.py", line 134, in CreateTranslator
return SubtitleTranslator(options, translation_provider)
File "/home/peter/repos/subtitles/gpt-subtrans-gemini/PySubtitle/SubtitleTranslator.py", line 68, in init
raise ProviderError(f"Unable to create provider client: {str(e)}")
PySubtitle.SubtitleError.ProviderError: Unable to create provider client: Model gemini-1.0-pro not found
Deactivating virtual environment...
```

Anyone has the same issue as me?

**Comment by machinewrapped** [comment]
I think it expects the model's display name, e.g. "Gemini 1.5 Flash" (in quotes).

It should be easy enough to support both though - can you try this branch?
https://github.com/machinewrapped/gpt-subtrans/tree/gemini-allow-true-names

**Comment by PeterDaveHello** [comment]
@machinewrapped LGTM, thanks!

**Comment by machinewrapped** [comment]
Thanks. Merged to main.
