### ISSUE TITLE
No module named regex

### ISSUE THREAD

**Issue by Lod3** [machinewrapped/gpt-subtrans#203]
I am trying to translate an extracted srt file from an mkv into english.
I have used the setup script for claude
And tried to install regex module separately
I cannot open the gui nor the command line version: 

```
 λ claude-subtrans "C:\Users\lode_\Videos\Transcriptiopns\ariaferma.srt" --target_language english
Traceback (most recent call last):
  File "C:\Users\lode_\gpt-subtrans\scripts\claude-subtrans.py", line 9, in <module>
    from scripts.subtrans_common import InitLogger, CreateArgParser, CreateOptions, CreateTranslator, CreateProject
  File "C:\Users\lode_\gpt-subtrans\scripts\subtrans_common.py", line 7, in <module>
    from PySubtitle.Helpers.Parse import ParseNames
  File "C:\Users\lode_\gpt-subtrans\PySubtitle\Helpers\__init__.py", line 5, in <module>
    import regex
ModuleNotFoundError: No module named 'regex' 
``` 

Any advice?

**Comment by machinewrapped** [comment]
Was this successfully resolved?

**Comment by Lod3** [comment]
I used the GUI but it crashed frequently 
Am going to check if I  can resolve it to use the cli
